name: Node.js CI/CD

on:
  push:
    branches:
      - main
      - develop
      - staging
  pull_request:
    branches:
      - main
      - develop
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [development, staging, production]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Create Firebase config
        run: echo ${{ secrets.FIREBASE_CONFIG }} > firebaseServices.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}

      - name: Install dependencies
        run: npm install

      # - name: Lint code
      #   run: npm run lint

      # - name: Run tests
      #   run: npm test

      - name: Build application
        run: npm run build
